services:
  api:
    container_name: api
    build:
      context: ./
      target: development # or "production"
    env_file: .env
    ports:
      - ${API_PORT}:3000
      - 9229:9229 # vscode debug port
    networks:
      - db-network
      - app-network
    volumes:
      - ./modules:/app/src/extra
      - ./extensions:/app/src/.hexabot/custom/extensions
      - api-data:/uploads
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: "wget --spider http://localhost:3000"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  ui:
    container_name: ui
    image: hexastack/hexabot-ui:latest
    env_file: .env
    ports:
      - ${APP_FRONTEND_PORT}:8080
    networks:
      - app-network
    depends_on:
      api:
        condition: service_healthy

  mongo:
    container_name: mongo
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - db-network
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017 --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - mongo-data:/data/db

  nlu-api:
    container_name: nlu-api
    image: hexastack/hexabot-nlu:latest
    env_file: .env
    networks:
      - nlu-network
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama-data:/root/.ollama
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    restart: unless-stopped
    networks:
      - ollama-network

volumes:
  mongo-data:
  api-data:
  ollama-data:

networks:
  db-network:
  app-network:
  nlu-network:
  ollama-network:
