version: '3.9'

services:
  ludwig-nlu-api:
    image: ludwigai/ludwig:master
    container_name: ludwig-nlu-api
    stdin_open: true
    tty: true
    env_file: ./.env
    command: >-
      multi_serve
      --model_paths '${LUDWIG_MODEL_PATHS}' --mode ${LUDWIG_NLU_MODE} --port ${LUDWIG_NLU_PORT} --host ${LUDWIG_NLU_HOST} 
    volumes:
      - ../ludwig-nlu/data:/data/data 
      - ../ludwig-nlu/results:/data/results
      - ../ludwig-nlu/cli.py:/usr/local/lib/python3.8/site-packages/ludwig/cli.py
      - ../ludwig-nlu/multi_serve.py:/usr/local/lib/python3.8/site-packages/ludwig/multi_serve.py
      - ludwig-nlu-repos:/data/repos
    networks:
      - ludwig-nlu-network
    ports:
      - "${LUDWIG_NLU_PORT}:${LUDWIG_NLU_PORT}"
      
  api:
    networks:
      - ludwig-nlu-network

volumes:
  ludwig-nlu-repos:

networks:
  ludwig-nlu-network:
