version: '3.9'

services:
  ludwig-nlu-api:
    image: ludwigai/ludwig:master
    container_name: ludwig-nlu-api
    stdin_open: true
    tty: true
    env_file: ./.env
    command: >-
      multi_serve
      --model_paths '${MODEL_PATHS}' --mode ${MODE} --port ${PORT} --host ${HOST} 
    volumes:
      - ../ludwig-nlu/data:/data 
      - ../ludwig-nlu/results:/results
      - ../ludwig-nlu/cli.py:/usr/local/lib/python3.8/site-packages/ludwig/cli.py
      - ../ludwig-nlu/multi_serve_hf.py:/usr/local/lib/python3.8/site-packages/ludwig/multi_serve_hf.py
      - ludwig-nlu-repos:/app/repos
    networks:
      - ludwig-nlu-network
    ports:
      - "${LUDWIG_NLU_PORT}:${LUDWIG_NLU_PORT}"
      
  api:
    networks:
      - ludwig-nlu-network

volumes:
  ludwig-nlu-repos:

networks:
  ludwig-nlu-network:
