version: '3.8'

services:
  ludwig-visualization:
    image: ludwigai/ludwig:master
    command: >
      visualize --visualization learning_curves
      --ground_truth_metadata /data/results/intent-classifier-lstm/model/training_set_metadata.json
      --training_statistics /data/results/intent-classifier-lstm/training_statistics.json
      --file_format png
      --output_directory /data/visualizations
    volumes:
      - ./visualizations:/data/visualizations
      - ./results:/data/results
    environment:
      - PYTHONUNBUFFERED=1  # Optional, to ensure logs are printed immediately
    networks:
      - default

networks:
  default:
    driver: bridge