version: '3.8'

services:
  ludwig:
    image: ludwigai/ludwig:master
    command: >
      experiment --config /data/src/${MODEL_NAME}.yaml
                 --dataset /data/data/train_data.json
                 --output_directory /data/results
    env_file:
      - .env
    volumes:
      - ./data:/data/data
      - ./src:/data/src
      - ./results:/data/results
