version: '3.8'

services:
  ludwig:
    image: ludwigai/ludwig:master
    stdin_open: true
    tty: true
    env_file: ./.env
    command: >-
      multi_serve
      --model_paths '${MODEL_PATHS}' --mode ${MODE} --port ${PORT} --host ${HOST} 
    volumes:
      - ./data:/data/data 
      - ./results:/data/results
      - ./cli.py:/usr/local/lib/python3.8/site-packages/ludwig/cli.py
      - ./multi_serve.py:/usr/local/lib/python3.8/site-packages/ludwig/multi_serve.py
      - nlu-repos:/data/repos

    ports:
      - "${PORT}:${PORT}" 
volumes:
  nlu-repos:
  