version: '3.8'

services:
  ludwig-predict:
    image: ludwigai/ludwig:master
    command: >
      predict
      --model_path /data/results/experiment_run/model
      --dataset /data/data/predict.csv
      --output_directory /data/predictions
    volumes:
      - ./data:/data/data
      - ./src:/data/src
      - ./results:/data/results
      - ./predictions:/data/predictions
      