version: '3.8'

services:
  ludwig:
    image: ludwigai/ludwig:master
    command: >
      experiment --config /src/${MODEL_NAME}.yaml
                 --dataset /data/train_data.json
                 --output_directory /results
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./src:/src
      - ./results/results
